language: node_js

node_js:
  - node

cache:
  directories:
    - node_modules

branchs:
  only:
    - master

services:
  - postgresql
  - elasticsearch
  - redis-server

install:
  - yarn install

before_script:
  - sleep 10

scripts:
  - yarn install codecov -g

after_success:
  - yarn codecov
