language: node_js

sudo: true

branchs:
  only:
    - master

services:
  - postgresql
  - elasticsearch
  - redis-server

node_js:
  - '12'

cache:
  directories:
    - node_modules

install:
  - yarn install

before_script:
  - sleep 10

script:
  - yarn test
  - yarn build

scripts:
  - yarn install codecov -g

after_success:
  - yarn codecov
