language: node_js

sudo: false

node_js:
  - node

cache:
  directories:
    - node_modules

branchs:
  only:
    - master

services:
  - postgresql
  - elasticsearch
  - redis-server

install:
  - npm install
  - npm install -g codecov

script:
  - npm test
  - npm build
  - codecov -f coverage/*.json

after_success:
  - npm codecov
